spring:
  application.name: OVY_Mq
  config:
    import: classpath:credential.yml
  server:
    port: 8080
  redis:
    host: localhost
    port: 6379

ovymq:
  task:
    active:
      consumer: false
      topic: true
    delay:
      topic: 5000
      consumer: 5000
