package io.github.jotabrc.ovy_mq_client.domain;

public enum Command {

    EXECUTE_CLIENT_SESSION_INITIALIZER,
    EXECUTE_CLIENT_SESSION_HANDLER_PUT_IF_ABSENT,
    EXECUTE_CLIENT_SESSION_HANDLER_REQUEST_MESSAGE,
    EXECUTE_CLIENT_MESSAGE_HANDLER_HANDLE_MESSAGE,
    EXECUTE_CLIENT_METHOD_HANDLER_PUT_IF_ABSENT,
    EXECUTE_CLIENT_METHOD_HANDLER_INVOKE
}
